### ISSUE TITLE
NBEATSx error on retrain, when callbacks defined

### ISSUE THREAD

**Issue by MC-Dave** [Nixtla/neuralforecast#393]
**Describe the bug**
Retraining a pre-trained model with callbacks enabled results in error. 

```python
Traceback (most recent call last):
  File "nf.py", line 145, in <module>
    nf.fit(df=train_df)
  File "/home/.../miniforge3/envs/.../lib/python3.8/site-packages/neuralforecast/core.py", line 157, in fit
    model.fit(self.dataset, val_size=val_size)
  File "/home/.../miniforge3/envs/.../lib/python3.8/site-packages/neuralforecast/common/_base_windows.py", line 493, in fit
    trainer.fit(self, datamodule=datamodule)
  File "/home/.../miniforge3/envs/.../lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 770, in fit
    self._call_and_handle_interrupt(
  File "/home/.../miniforge3/envs/.../lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 723, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/.../miniforge3/envs/.../lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 811, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/home/.../miniforge3/envs/.../lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1224, in _run
    self._log_hyperparams()
  File "/home/.../miniforge3/envs/.../lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1294, in _log_hyperparams
    logger.save()
  File "/home/.../miniforge3/envs/.../lib/python3.8/site-packages/pytorch_lightning/utilities/rank_zero.py", line 32, in wrapped_fn
    return fn(*args, **kwargs)
  File "/home/.../miniforge3/envs/.../lib/python3.8/site-packages/pytorch_lightning/loggers/tensorboard.py", line 266, in save
    save_hparams_to_yaml(hparams_file, self.hparams)
  File "/home/.../miniforge3/envs/.../lib/python3.8/site-packages/pytorch_lightning/core/saving.py", line 402, in save_hparams_to_yaml
    yaml.dump(v)
  File "/home/.../miniforge3/envs/.../lib/python3.8/site-packages/yaml/__init__.py", line 290, in dump
    return dump_all([data], stream, Dumper=Dumper, **kwds)
  File "/home/.../miniforge3/envs/.../lib/python3.8/site-packages/yaml/__init__.py", line 278, in dump_all
    dumper.represent(data)
  File "/home/.../miniforge3/envs/.../lib/python3.8/site-packages/yaml/representer.py", line 27, in represent
    node = self.represent_data(data)
  File "/home/.../miniforge3/envs/.../lib/python3.8/site-packages/yaml/representer.py", line 48, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/home/.../miniforge3/envs/.../lib/python3.8/site-packages/yaml/representer.py", line 199, in represent_list
    return self.represent_sequence('tag:yaml.org,2002:seq', data)
  File "/home/.../miniforge3/envs/.../lib/python3.8/site-packages/yaml/representer.py", line 92, in represent_sequence
    node_item = self.represent_data(item)
  File "/home/.../miniforge3/envs/.../lib/python3.8/site-packages/yaml/representer.py", line 52, in represent_data
    node = self.yaml_multi_representers[data_type](self, data)
  File "/home/.../miniforge3/envs/.../lib/python3.8/site-packages/yaml/representer.py", line 342, in represent_object
    return self.represent_mapping(
  File "/home/.../miniforge3/envs/.../lib/python3.8/site-packages/yaml/representer.py", line 118, in represent_mapping
    node_value = self.represent_data(item_value)
  File "/home/.../miniforge3/envs/.../lib/python3.8/site-packages/yaml/representer.py", line 52, in represent_data
    node = self.yaml_multi_representers[data_type](self, data)
  File "/home/.../miniforge3/envs/.../lib/python3.8/site-packages/yaml/representer.py", line 346, in represent_object
    return self.represent_sequence(tag+function_name, args)
  File "/home/.../miniforge3/envs/.../lib/python3.8/site-packages/yaml/representer.py", line 92, in represent_sequence
    node_item = self.represent_data(item)
  File "/home/.../miniforge3/envs/.../lib/python3.8/site-packages/yaml/representer.py", line 52, in represent_data
    node = self.yaml_multi_representers[data_type](self, data)
  File "/home/.../miniforge3/envs/.../lib/python3.8/site-packages/yaml/representer.py", line 342, in represent_object
    return self.represent_mapping(
  File "/home/.../miniforge3/envs/.../lib/python3.8/site-packages/yaml/representer.py", line 118, in represent_mapping
    node_value = self.represent_data(item_value)
  File "/home/.../miniforge3/envs/.../lib/python3.8/site-packages/yaml/representer.py", line 52, in represent_data
    node = self.yaml_multi_representers[data_type](self, data)
  File "/home/.../miniforge3/envs/.../lib/python3.8/site-packages/yaml/representer.py", line 330, in represent_object
    dictitems = dict(dictitems)
ValueError: dictionary update sequence element #0 has length 1; 2 is required
```

**To Reproduce**

1. Train the initial model for x epochs and save it
```python 
    df = pd.read_csv(data_fp, parse_dates=['ds'])
    train_df, val_df = df[:-validate_holdout], df[-validate_holdout:]

    loss = QuantileLoss(q=0.5)

    early_stop_callback = EarlyStopping(
        monitor="train_loss_epoch",
        min_delta=0.00001,
        patience=1500,
        mode="min",
        verbose=False
    )

    callbacks = [
        early_stop_callback,
    ]

    models = [
        NBEATSx(
            h=horizon,
            input_size=input_size,
            futr_exog_list=future_exog,  # <- Future exogenous variables
            hist_exog_list=historic_exog,  # <- Historical exogenous variables

            learning_rate=1e-5,
            batch_size=32,
            windows_batch_size=1024,
            max_epochs=40,

            n_harmonics=8, 
            n_polynomials=6,  
            stack_types=["identity", "trend", "seasonality"],
            n_blocks=[1, 1, 1],
            mlp_units=[[32, 32], [32, 32], [32, 32]],

            activation="ReLU",
            shared_weights=False,
            loss=loss,
            scaler_type="robust",

            # trainer args
            callbacks=callbacks,
            num_lr_decays=0,
        )
    ]

    nf = NeuralForecast(models=models, freq='H')
    nf.fit(df=train_df)
    nf.save('bbbb', overwrite=True)
```

2. Load and attempt to retrain the model (change last three lines to ...)

```python
    nf = NeuralForecast.load('bbbb')
    nf.fit(df=train_df)
    nf.save('bbbb', overwrite=True)
```
After step 2, you will receive the above error. 

3. Retry steps 1 & 2, commenting out the `callbacks=callbacks` argument passed to `NBEATSx`. It should save, load, and retrain without error. Only when including the callbacks to the model definition does it fail to retrain after save/load.

**Expected behavior**
The model should be re-trainable after loading. 

**Desktop (please complete the following information):**
 - OS: Ubuntu MATE 20.04 x64
 - Python 3.8.13
 - NeuralForecast 1.3.0

**Comment by cchallu** [comment]
Hi @MC-Dave! Thanks for discovering the bug and the detailed issue.

Indeed, fitting the model again with callbacks raises an error.

In the latest changes, we added an `early_stop_patience_steps` hyperparameter, and the creation of the callback is done internally. Can you try using this instead?

**Comment by MC-Dave** [comment]
@cchallu Thank you for the response! Are there options for setting min_delta? 

I assume there is not yet any formal docs on it. Let me know if there are any related issues I could review for more info.

**Comment by MC-Dave** [comment]
@cchallu After pulling from main slightly editing to fit my needs, and installing, I am able to successfully save/load and re-train a model with early stopping callback. However, it does not seem the earlystopping is working. If i set `early_stop_patience_steps` to 1 and the `min_delta` to an absurdly high number, it never stops training early. 

I updated the code in `BaseWindows` class to hardcode additional config for the earlystopping callback

```python
EarlyStopping(
    monitor="ptl/val_loss", patience=self.early_stop_patience_steps,
    min_delta=1000000000.00001,
    mode="min",
    verbose=False
)
```

**Comment by cchallu** [comment]
By default, the `validation_loss` is computed every 100 training steps (use the new `val_check_steps` hyperparameter to change it). The patience is the number of times the validation_loss does not increase. Do you have less than 100 steps in your current experiment? Can you change `val_check_steps` to a smaller number?

We confirmed the early stopping is working in the Usage example code of each model. See https://github.com/Nixtla/neuralforecast/blob/main/nbs/models.nhits.ipynb for example.

**Comment by MC-Dave** [comment]
@cchallu I wasn't letting it run long enough. 

I now receive the following error. It doesn't appear there is a way to dynamically change the monitor value, so I have hardcoded the change locally for now

```python
Epoch 0: 100%|████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00,  2.51it/s, loss=0.33, v_num=230, train_loss_step=0.330, train_loss_epoch=0.330]Traceback (most recent call last):                                                                                                                                                                           
  File "nf.py", line 112, in <module>
    nf.fit(df=train_df)
  File "/home/.../src/neuralforecast/neuralforecast/core.py", line 175, in fit
    model.fit(self.dataset, val_size=val_size)
  File "/home/.../src/neuralforecast/neuralforecast/common/_base_windows.py", line 547, in fit
    trainer.fit(self, datamodule=datamodule)
  File "/home/.../miniforge3/envs//.../lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 770, in fit
    self._call_and_handle_interrupt(
  File "/home/.../miniforge3/envs//.../lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 723, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/.../miniforge3/envs//.../lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 811, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/home/.../miniforge3/envs//.../lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1236, in _run
    results = self._run_stage()
  File "/home/.../miniforge3/envs//.../lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1323, in _run_stage
    return self._run_train()
  File "/home/.../miniforge3/envs//.../lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1353, in _run_train
    self.fit_loop.run()
  File "/home/.../miniforge3/envs//.../lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 205, in run
    self.on_advance_end()
  File "/home/.../miniforge3/envs//.../lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 294, in on_advance_end
    self.trainer._call_callback_hooks("on_train_epoch_end")
  File "/home/.../miniforge3/envs//.../lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1636, in _call_callback_hooks
    fn(self, self.lightning_module, *args, **kwargs)
  File "/home/.../miniforge3/envs//.../lib/python3.8/site-packages/pytorch_lightning/callbacks/early_stopping.py", line 179, in on_train_epoch_end
    self._run_early_stopping_check(trainer)
  File "/home/.../miniforge3/envs//.../lib/python3.8/site-packages/pytorch_lightning/callbacks/early_stopping.py", line 190, in _run_early_stopping_check
    if trainer.fast_dev_run or not self._validate_condition_metric(  # disable early_stopping with fast_dev_run
  File "/home/.../miniforge3/envs//.../lib/python3.8/site-packages/pytorch_lightning/callbacks/early_stopping.py", line 145, in _validate_condition_metric
    raise RuntimeError(error_msg)
RuntimeError: Early stopping conditioned on metric `ptl/val_loss` which is not available. Pass in or modify your `EarlyStopping` callback to use any of the following: `train_loss`, `train_loss_step`, `train_loss_epoch`
```

**Comment by cchallu** [comment]
The val_loss is not available when you do not define the validation set. Use the `val_size` input of the `fit` function.

**Comment by MC-Dave** [comment]
@cchallu When I set the val-size to a number > 0, it makes each epoch take about 10x longer to run. The train epoch runs normal speed, but the validation takes a couple seconds every epoch. Should there not be a parameter to allow for specifying a different monitor metric?

**Comment by cchallu** [comment]
The standard practice is to do early stopping on the validation set, as it is used to avoid overfitting your training data. Instead of using the training error with early stopping, it is easier to control the number of epochs/steps directly.

To make it faster, you can reduce the frequency of the validation loss with `val_check_steps`. The number of steps per epoch is num_series/batch_size; if `val_check_steps` is smaller, you are computing the validation loss multiple times per epoch.

We are considering changing the training to training steps instead of epochs. I recommend using `max_steps` instead of `max_epochs` since  `val_check_steps` and learning rate decay can be more easily controlled. The `NBEATSx` (and `NHITS`) models should work very well with only 1000 steps in small (<1000 time series) datasets.

**Comment by MC-Dave** [comment]
@cchallu Thank you for your help! Enabled validation and use val_check_steps to control how often it validates. 

This is a great project, by the way. Thank you!
