### ISSUE TITLE
[DeepAR] ImportError: cannot import name 'DeepAR' from 'neuralforecast.models'

### ISSUE THREAD

**Issue by manikTharaka** [Nixtla/neuralforecast#699]
### What happened + What you expected to happen

In google Colab I tried running the following code derived from the [docs](https://nixtla.github.io/neuralforecast/models.deepar.html)

```import pandas as pd
import pytorch_lightning as pl
import matplotlib.pyplot as plt

from neuralforecast import NeuralForecast
from neuralforecast.models import DeepAR
from neuralforecast.losses.pytorch import DistributionLoss, HuberMQLoss
from neuralforecast.tsdataset import TimeSeriesDataset
from neuralforecast.utils import AirPassengers, AirPassengersPanel, AirPassengersStatic

#AirPassengersPanel['y'] = AirPassengersPanel['y'] + 10
Y_train_df = AirPassengersPanel[AirPassengersPanel.ds<AirPassengersPanel['ds'].values[-12]] # 132 train
Y_test_df = AirPassengersPanel[AirPassengersPanel.ds>=AirPassengersPanel['ds'].values[-12]].reset_index(drop=True) # 12 test

nf = NeuralForecast(
    models=[DeepAR(h=12,
                   input_size=48,
                   lstm_n_layers=3,
                   trajectory_samples=100,
                   loss=DistributionLoss(distribution='Normal', level=[80, 90], return_params=False),
                   learning_rate=0.005,
                   stat_exog_list=['airline1'],
                   futr_exog_list=['trend'],
                   max_steps=100,
                   val_check_steps=10,
                   early_stop_patience_steps=-1,
                   scaler_type='standard',
                   enable_progress_bar=True),
    ],
    freq='M'
)
```
which resulted in the following import error:

```
---------------------------------------------------------------------------

ImportError                               Traceback (most recent call last)

[<ipython-input-8-39b01eb3e882>](https://localhost:8080/#) in <cell line: 6>()
      4 
      5 from neuralforecast import NeuralForecast
----> 6 from neuralforecast.models import DeepAR
      7 from neuralforecast.losses.pytorch import DistributionLoss, HuberMQLoss
      8 from neuralforecast.tsdataset import TimeSeriesDataset

ImportError: cannot import name 'DeepAR' from 'neuralforecast.models' (/usr/local/lib/python3.10/dist-packages/neuralforecast/models/__init__.py)


---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
```
Further inspection into the __init__.py file gave the following results:
```
!cat /usr/local/lib/python3.10/dist-packages/neuralforecast/models/__init__.py

__all__ = ['RNN', 'GRU', 'LSTM', 'TCN', 'DilatedRNN',
           'MLP', 'NHITS', 'NBEATS', 'NBEATSx',
           'TFT', 'VanillaTransformer', 'Informer', 'Autoformer', 'PatchTST', 'FEDformer',
           'StemGNN', 'HINT']

from .rnn import RNN
from .gru import GRU
from .lstm import LSTM
from .tcn import TCN
from .dilated_rnn import DilatedRNN
from .mlp import MLP
from .nhits import NHITS
from .nbeats import NBEATS
from .nbeatsx import NBEATSx
from .tft import TFT
from .stemgnn import StemGNN
from .vanillatransformer import VanillaTransformer
from .informer import Informer
from .autoformer import Autoformer
from .fedformer import FEDformer
from .patchtst import PatchTST
from .hint import HINT
```
However I cloned the git repo locally and followed the instructions given in contributing section. When I ran a similar test using the main branch the DeepAR import didn't have any issues. But then the following error was encountered:

```
Traceback (most recent call last):
  File "/home/manik/dev/neuralforecast/test.py", line 32, in <module>
    nf.fit(df=Y_train_df, static_df=AirPassengersStatic, val_size=12)
  File "/home/manik/dev/neuralforecast/neuralforecast/core.py", line 261, in fit
    model.fit(self.dataset, val_size=val_size)
  File "/home/manik/dev/neuralforecast/neuralforecast/common/_base_windows.py", line 682, in fit
    trainer = pl.Trainer(**self.trainer_kwargs)
  File "/home/manik/miniconda3/envs/neuralforecast/lib/python3.10/site-packages/pytorch_lightning/utilities/argparse.py", line 339, in insert_env_defaults
    return fn(self, **kwargs)
  File "/home/manik/miniconda3/envs/neuralforecast/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 564, in __init__
    self._data_connector.on_trainer_init(
  File "/home/manik/miniconda3/envs/neuralforecast/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/data_connector.py", line 89, in on_trainer_init
    raise MisconfigurationException(
pytorch_lightning.utilities.exceptions.MisconfigurationException: check_val_every_n_epoch should be an integer. Found None
```

Assume this is an issue with latest DeepAR changes not being incorporated to the build ?

### Versions / Dependencies

Issue was observed on both versions 1.6.0 and 1.5.0 installed by pip in google Colab

### Reproduction script

```
from neuralforecast import NeuralForecast
from neuralforecast.models import DeepAR
from neuralforecast.losses.pytorch import DistributionLoss,HuberMQLoss
from neuralforecast.tsdataset import TimeSeriesDataset
from neuralforecast.utils import AirPassengers, AirPassengersPanel, AirPassengersStatic

#AirPassengersPanel['y'] = AirPassengersPanel['y'] + 10
Y_train_df = AirPassengersPanel[AirPassengersPanel.ds<AirPassengersPanel['ds'].values[-12]] # 132 train
Y_test_df = AirPassengersPanel[AirPassengersPanel.ds>=AirPassengersPanel['ds'].values[-12]].reset_index(drop=True) # 12 test

nf = NeuralForecast(
    models=[DeepAR(h=12,
                   input_size=48,
                   lstm_n_layers=3,
                   trajectory_samples=100,
                   loss=DistributionLoss(distribution='Normal', level=[80, 90], return_params=False),
                   learning_rate=0.005,
                   stat_exog_list=['airline1'],
                   futr_exog_list=['trend'],
                   max_steps=100,
                   val_check_steps=10,
                   early_stop_patience_steps=-1,
                   scaler_type='standard',
                   enable_progress_bar=True),
    ],
    freq='M'
)
nf.fit(df=Y_train_df, static_df=AirPassengersStatic, val_size=12)
Y_hat_df = nf.predict(futr_df=Y_test_df)
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

**Comment by candalfigomoro** [comment]
DeepAR has been added in version 1.6.1, so there's no DeepAR in versions 1.5.0 and 1.6.0

**Comment by manikTharaka** [comment]
Got it, seems to be working with 1.6.1. Thanks for the response. I see that 1.6.1 was released only today but there was an entry for the DeepAR model already in the documentation, thats why I was confused. Will mark this as resolved.
