### ISSUE TITLE
Large dataset training has Out of Memory Error!!!

### ISSUE THREAD

**Issue by lk1983823** [Nixtla/neuralforecast#783]
Thank you for the great work. I find neural forecast very useful for my job. However, when I try to use TFT or NHITS to train a larger dataset with the shape of (1089214, 32) and only one unique_id. It shows out of memory error using cuda, no matter of the size of the batch_size or the number of devices. Here is my code:

```
horizon = 30
hist_length = 120
model = [TFT(
                input_size=hist_length,
                h=horizon, 
                max_steps=30, 
                hist_exog_list=ex_columns,
                batch_size=32, 
                accelerator='gpu',
                devices=2
               )]
nf = NeuralForecast(models=model, freq='S')
nf.fit(df=data, verbose=True) # data shape (1089214, 32)
```
The number of the ex_columns is 12.
The error is as folliows:
```
TS_HX_seconds_NHITS.py
(1089214, 32)
Seed set to 1
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
2023-10-14 14:30:38.507963: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-10-14 14:30:39.278753: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/lib64
2023-10-14 14:30:39.278834: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/lib64
2023-10-14 14:30:39.278844: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Epoch 0:   0%|                                                                                                                                | 0/1 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/media/lk/disk1/DL_lk/202205_RZ_GAN模型/model/EvoOpt/RZ_LT_TS_HX_seconds_NHITS.py", line 113, in <module>
    nf.fit(df=df_train[:], verbose=True)
  File "/home/lk/anaconda3/envs/dpc/lib/python3.8/site-packages/neuralforecast/core.py", line 274, in fit
    model.fit(self.dataset, val_size=val_size)
  File "/home/lk/anaconda3/envs/dpc/lib/python3.8/site-packages/neuralforecast/common/_base_windows.py", line 734, in fit
    trainer.fit(self, datamodule=datamodule)
  File "/home/lk/anaconda3/envs/dpc/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 545, in fit
    call._call_and_handle_interrupt(
  File "/home/lk/anaconda3/envs/dpc/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/lk/anaconda3/envs/dpc/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 581, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/lk/anaconda3/envs/dpc/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 990, in _run
    results = self._run_stage()
  File "/home/lk/anaconda3/envs/dpc/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1036, in _run_stage
    self.fit_loop.run()
  File "/home/lk/anaconda3/envs/dpc/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 202, in run
    self.advance()
  File "/home/lk/anaconda3/envs/dpc/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 359, in advance
    self.epoch_loop.run(self._data_fetcher)
  File "/home/lk/anaconda3/envs/dpc/lib/python3.8/site-packages/pytorch_lightning/loops/training_epoch_loop.py", line 136, in run
    self.advance(data_fetcher)
  File "/home/lk/anaconda3/envs/dpc/lib/python3.8/site-packages/pytorch_lightning/loops/training_epoch_loop.py", line 240, in advance
    batch_output = self.automatic_optimization.run(trainer.optimizers[0], batch_idx, kwargs)
  File "/home/lk/anaconda3/envs/dpc/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/automatic.py", line 187, in run
    self._optimizer_step(batch_idx, closure)
  File "/home/lk/anaconda3/envs/dpc/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/automatic.py", line 265, in _optimizer_step
    call._call_lightning_module_hook(
  File "/home/lk/anaconda3/envs/dpc/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 157, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/home/lk/anaconda3/envs/dpc/lib/python3.8/site-packages/pytorch_lightning/core/module.py", line 1282, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "/home/lk/anaconda3/envs/dpc/lib/python3.8/site-packages/pytorch_lightning/core/optimizer.py", line 151, in step
    step_output = self._strategy.optimizer_step(self._optimizer, closure, **kwargs)
  File "/home/lk/anaconda3/envs/dpc/lib/python3.8/site-packages/pytorch_lightning/strategies/strategy.py", line 230, in optimizer_step
    return self.precision_plugin.optimizer_step(optimizer, model=model, closure=closure, **kwargs)
  File "/home/lk/anaconda3/envs/dpc/lib/python3.8/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 117, in optimizer_step
    return optimizer.step(closure=closure, **kwargs)
  File "/home/lk/anaconda3/envs/dpc/lib/python3.8/site-packages/torch/optim/lr_scheduler.py", line 69, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/lk/anaconda3/envs/dpc/lib/python3.8/site-packages/torch/optim/optimizer.py", line 280, in wrapper
    out = func(*args, **kwargs)
  File "/home/lk/anaconda3/envs/dpc/lib/python3.8/site-packages/torch/optim/optimizer.py", line 33, in _use_grad
    ret = func(self, *args, **kwargs)
  File "/home/lk/anaconda3/envs/dpc/lib/python3.8/site-packages/torch/optim/adam.py", line 121, in step
    loss = closure()
  File "/home/lk/anaconda3/envs/dpc/lib/python3.8/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 104, in _wrap_closure
    closure_result = closure()
  File "/home/lk/anaconda3/envs/dpc/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/automatic.py", line 140, in __call__
    self._result = self.closure(*args, **kwargs)
  File "/home/lk/anaconda3/envs/dpc/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/lk/anaconda3/envs/dpc/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/automatic.py", line 126, in closure
    step_output = self._step_fn()
  File "/home/lk/anaconda3/envs/dpc/lib/python3.8/site-packages/pytorch_lightning/loops/optimization/automatic.py", line 315, in _training_step
    training_step_output = call._call_strategy_hook(trainer, "training_step", *kwargs.values())
  File "/home/lk/anaconda3/envs/dpc/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 309, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/home/lk/anaconda3/envs/dpc/lib/python3.8/site-packages/pytorch_lightning/strategies/strategy.py", line 382, in training_step
    return self.lightning_module.training_step(*args, **kwargs)
  File "/home/lk/anaconda3/envs/dpc/lib/python3.8/site-packages/neuralforecast/common/_base_windows.py", line 446, in training_step
    windows = self._create_windows(batch, step="train")
  File "/home/lk/anaconda3/envs/dpc/lib/python3.8/site-packages/neuralforecast/common/_base_windows.py", line 214, in _create_windows
    windows = windows.permute(0, 2, 3, 1).contiguous()
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 7.95 GiB (GPU 0; 7.80 GiB total capacity; 124.91 MiB already allocated; 7.43 GiB free; 130.00 MiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF 
```
I try to set a smaller batch_size to save more cuda memory, but it doesn't work. But when I use just a small part of training data, like the first 5000 rows, the code finally runs well.  Is the whole data put into the gpu memory at once during training? 
Following the code, I find that in the function training_step in _base_windows.py, the batch["temporal"] has the shape of (1, 14,1089214). Why the whole data is considered as one batch ?

Is there anyone can help? Thanks!

**Comment by cchallu** [comment]
Hi @lk1983823 ! Yes, this is a current known limitation. The model is first creating all the possible windows of the train set, before sampling a subset of size `windows_batch_size`.  This is more efficient but will run out of memory for large datasets. Two alternatives are:
- Remove the earliest history. So you train the model, for example, only on the latest 100,000 data points.
- Step `step_size=30` (horizon), will reduce the number of windows created by 30x.
Also, try setting `batch_size=1`, and `inference_windows_batch_size` to a lower number (if you have a validation set)

We are working on solving this issue by creating a smaller subset of the entire time series before creating the windows.

**Comment by lk1983823** [comment]
@cchallu Thanks. I think I solve the problem by split the entire dataset with multiple unique_ids. Therefore, there are many sub-series to be trained.
