### ISSUE TITLE
Kernel crash on documentation notebook LongHorizon_Probabilistic.ipynb

### ISSUE THREAD

**Issue by Karlheinzniebuhr** [Nixtla/neuralforecast#784]
### What happened + What you expected to happen

I tried executing [LongHorizon_Probabilistic.ipynb](https://colab.research.google.com/github/Nixtla/neuralforecast/blob/main/nbs/examples/LongHorizon_Probabilistic.ipynb#scrollTo=jK4ZiJ-CnUO-) locally as well as on google colab. It exits with the following error:

```
2023-10-14 19:55:02,573	WARNING worker.py:2058 -- A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: ffffffffffffffff515b9086356f445f93b4cf0301000000 Worker ID: 107c2395b0b98ed2cab097dd16eb66fe46c590a840a1173097f5d464 Node ID: d67469e3b019a354c561effc5267c000dc73b612177592d0d3227281 Worker IP address: 172.28.0.12 Worker port: 35867 Worker PID: 3451 Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.
2023-10-14 19:55:02,590	ERROR tune_controller.py:1502 -- Trial task failed for trial _train_tune_14c48_00000
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/ray/air/execution/_internal/event_manager.py", line 110, in resolve_future
    result = ray.get(future)
  File "/usr/local/lib/python3.10/dist-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ray/_private/worker.py", line 2549, in get
    raise value
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.
	class_name: ImplicitFunc
	actor_id: 515b9086356f445f93b4cf0301000000
	pid: 3451
	namespace: a8256fbd-5259-43d1-973f-f3dda32567b6
	ip: 172.28.0.12
The actor is dead because its worker process has died. Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.
```

### Versions / Dependencies

Latest pip version:
`!pip install neuralforecast datasetsforecast`

### Reproduction script

[Vanilla jupyter notebook from the documentation](https://colab.research.google.com/github/Nixtla/neuralforecast/blob/main/nbs/examples/LongHorizon_Probabilistic.ipynb#scrollTo=9AgwnEWvwEe7)

### Issue Severity

High: It blocks me from completing my task.

**Comment by marcopeix** [comment]
Can't reproduce. The example works well on Google Colab on a free T4 instance. Use the link provided on [this page](https://nixtlaverse.nixtla.io/neuralforecast/docs/tutorials/longhorizon_nhits.html) of the documentation.
